class_name Keys
extends RefCounted

# The highest-frequency dictionary keys in the live tree. Boundary code uses
# these names so misspellings fail at parse time instead of returning defaults.
const ID := "id"
const OK := "ok"
const STATE := "state"
const LABEL := "label"
const UI_STATE := "ui_state"
const ARCHETYPE_ID := "archetype_id"
const MESSAGE := "message"
const KIND := "kind"
const STATUS := "status"
const DISPLAY_NAME := "display_name"
const ERRORS := "errors"
const GAME_STATES := "game_states"
const X := "x"
const BANKROLL_DELTA := "bankroll_delta"
const TYPE := "type"
const ENABLED := "enabled"
const RUN_STATE := "run_state"
const ACTIVE := "active"
const Y := "y"
const EVENT_ID := "event_id"
const SUSPICION_DELTA := "suspicion_delta"
const VISIBLE := "visible"
const NODE_ID := "node_id"
const TIER := "tier"
const MODE := "mode"
const STABLE_OBJECT_ID := "stable_object_id"
const ACTION_ID := "action_id"
const PHASE_ID := "phase_id"
const OUTCOME := "outcome"
const PAYOUT := "payout"
const OWNER_NAMESPACE := "owner_namespace"
const OBJECT_ID := "object_id"
const NAME := "name"
const SEMANTIC_STATE := "semantic_state"
const RECT := "rect"
const INSTANCE_ID := "instance_id"
const SCHEMA_VERSION := "schema_version"
const AVAILABLE := "available"
const SPEAKER := "speaker"
const PHASE := "phase"
