param([string]$OutPath = "data/environments/scenario_sequences/env06_7_queen_public.json")

$ErrorActionPreference = "Stop"

$specs = @(
    @{ id="delta_queen_wedding_charter"; place="delta_queen"; title="Wedding Charter"; arrival="Ceremony ropes split the promenade while a ring case and guest cart block opposite deck lanes."; verbs=@("inspect_ring_case","route_guests","deliver_rings"); objects=@("ring_case","guest_cart","ceremony_rope"); actor="deck_coordinator"; outcomes=@("ceremony","delay","broken_charter","interrupted"); connection="travel_departed"; pressure="timed_procession" },
    @{ id="delta_queen_whale_aboard"; place="delta_queen"; title="Whale Aboard"; arrival="An entourage advances between a guarded salon and a reserved premium table, closing each lane behind it."; verbs=@("observe_entourage","carry_service_tray","choose_access_route"); objects=@("premium_table","service_tray","guard_post"); actor="whale_host"; outcomes=@("earned_access","avoided_attention","security_lock","interrupted"); connection="game_result"; pressure="moving_security" },
    @{ id="delta_queen_fog_delay"; place="delta_queen"; title="Fog Delay"; arrival="Fog shutters the gangway while a chart board and signal lamp open two competing navigation stations."; verbs=@("read_chart_board","sound_depth_line","choose_dock_plan"); objects=@("chart_board","signal_lamp","closed_gangway"); actor="deck_officer"; outcomes=@("assisted_reroute","safe_wait","missed_window","interrupted"); connection="town_transition"; pressure="visibility_closure" },
    @{ id="delta_queen_engine_trouble"; place="delta_queen"; title="Engine Trouble"; arrival="A hot bulkhead seals the lower deck while a parts trolley and silent pressure gauge mark the repair route."; verbs=@("diagnose_pressure","fetch_impeller_key","apply_repair"); objects=@("pressure_gauge","parts_trolley","sealed_bulkhead","evacuation_bench"); actor="engine_mate"; outcomes=@("travel_resumed","limited_power","evacuation_staged","interrupted"); connection="world_boundary"; pressure="power_decay" },
    @{ id="delta_queen_captains_invitational"; place="delta_queen"; title="Captain's Invitational"; arrival="Three bracket tables and a scorer rail replace the open deck while spectators occupy the eliminated lanes."; verbs=@("verify_entry_card","track_bracket","officiate_result","seat_finalists"); objects=@("entry_table","bracket_board","final_table","spectator_rail"); actor="tournament_scorer"; outcomes=@("qualified_final","observed_final","disputed_final","interrupted"); connection="game_result"; pressure="elimination_rounds" },
    @{ id="grand_casino_gala_night"; place="grand_casino"; title="Gala Night"; arrival="Coat check, velvet ropes, and a stalled stage lift replace the ordinary path to the casino floor."; verbs=@("check_coat_token","verify_invitation","reset_stage_lift"); objects=@("coat_check","vip_rope","stage_lift"); actor="gala_host"; outcomes=@("vip_route","public_reopening","gala_failure","interrupted"); connection="service_result"; pressure="credential_deadline" },
    @{ id="grand_casino_convention_crowd"; place="grand_casino"; title="Convention Crowd"; arrival="Delegation placards reserve two machine banks while a booking board sends both groups toward one table block."; verbs=@("inspect_booking_board","move_delegation_markers","mediate_block_swap"); objects=@("booking_board","machine_block_a","machine_block_b","table_block"); actor="convention_coordinator"; outcomes=@("blocks_relocated","split_schedule","floor_standoff","interrupted"); connection="game_result"; pressure="reservation_rotation" },
    @{ id="grand_casino_audit_night"; place="grand_casino"; title="Audit Night"; arrival="Auditors move from cage seal to pit ledger while staff close each inspected zone behind them."; verbs=@("acknowledge_audit_route","present_pit_ledger","choose_audit_response"); objects=@("cage_seal","pit_ledger","audit_barrier","open_exit_marker"); actor="lead_auditor"; outcomes=@("compliant_floor","redirected_audit","closed_games","interrupted"); connection="heat_band_changed"; pressure="visible_zone_sweep" }
)

function New-SceneOp([string]$sid,[string]$id,[string]$state,[int]$index) {
    return [ordered]@{ family="scene_ops"; op="spawn"; receipt_id="${sid}_${id}_${state}"; owner_namespace="scenario"; stable_object_id=$id; object=[ordered]@{ label=($id -replace '_',' '); role=$(if($index -eq 0){"workstation"}else{"prop"}); zone_id=@("left","center","right","background","foreground")[$index % 5]; bounds=[ordered]@{w=48 + ($index*8);h=48 + (($index%2)*8)}; visible=$true; enabled=$true; state=$state; appearance="${id}_${state}" } }
}

function New-InteractionOp([string]$sid,[string]$target,[string]$verb,[int]$order,[bool]$safeExit=$false) {
    return [ordered]@{ family="interaction_ops"; op="add"; receipt_id="${sid}_${target}_${verb}_controls"; owner_namespace="scenario"; stable_object_id=$target; interaction=[ordered]@{ owner_namespace="scenario"; stable_object_id=$target; label=($target -replace '_',' '); state_label="Action ready"; prompt=(($verb -replace '_',' ') + "."); enabled=$true; disabled_reason=""; available_actions=@([ordered]@{id=$verb;label=($verb -replace '_',' ');input_action=$(if($safeExit){"ui_cancel"}else{"ui_accept"});non_color_state=$verb;handler="publish_feedback";inputs=[ordered]@{message=(($verb -replace '_',' ') + " is recorded at this boundary.")}}); input_actions=@($(if($safeExit){"ui_cancel"}else{"ui_accept"})); non_color_state=$(if($safeExit){"safe_exit"}else{"action_ready"}); focus_order=$order; hit_bounds=[ordered]@{w=56;h=56}; min_target_size=44; safe_exit=$safeExit; alternate_exit=$false } }
}

function New-ActorOp([string]$sid,[string]$actor,[string]$phase,[int]$index) {
    return [ordered]@{ family="actor_ops"; op="spawn"; receipt_id="${sid}_${actor}_${phase}"; owner_namespace="scenario"; stable_object_id=$actor; actor=[ordered]@{label=($actor -replace '_',' ');actor_id=$actor;anchor_id="${actor}_anchor";behavior=@("observe","work","move","guard")[$index%4];route_id="${actor}_route";pose=$phase} }
}

function New-Scenario($spec) {
    $sid=$spec.id; $verbs=@($spec.verbs); $objects=@($spec.objects); $outcomes=@($spec.outcomes)
    $phases=@(); $objectiveSteps=@()
    for($i=0;$i -lt $verbs.Count;$i++) {
        $phaseId=$(if($i -eq 0){"arrival"}else{"beat_$i"}); $next=$(if($i -eq $verbs.Count-1){"resolution"}else{"beat_$($i+1)"})
        $sceneOps=@(); if($i -eq 0){ for($j=0;$j -lt $objects.Count;$j++){ $sceneOps += New-SceneOp $sid $objects[$j] "arrival" $j } } else { $sceneOps += New-SceneOp $sid $objects[$i % $objects.Count] "beat_$i" $i }
        $interactions=@(New-InteractionOp $sid $objects[$i % $objects.Count] $verbs[$i] ($i+1)); if($i -eq 0){ $interactions += New-InteractionOp $sid "safe_exit" "leave_sequence" 90 $true }
        $branches=@([ordered]@{id="${phaseId}_advance";condition=[ordered]@{type="command";command_id=$verbs[$i]};next_phase=$next},[ordered]@{id="${phaseId}_refuse";condition=[ordered]@{type="command";command_id="refuse_sequence"};next_phase="resolution"},[ordered]@{id="${phaseId}_depart";condition=[ordered]@{type="fact";fact_type="travel_departed"};next_phase="resolution"})
        $phaseLabel = if($i -eq 0){$spec.title}else{($verbs[$i] -replace '_',' ')}
        $arrivalFeedback = if($i -eq 0){$spec.arrival}else{"The room changes after " + ($verbs[$i-1] -replace '_',' ') + "."}
        $phases += [ordered]@{id=$phaseId;label=$phaseLabel;arrival_feedback=$arrivalFeedback;exit_prompt="The marked exit remains usable without completing the sequence.";entry_conditions=@([ordered]@{type="always"});objective_ids=@("${sid}_objective");advance_after_actions=$i;scene_ops=$sceneOps;interaction_ops=$interactions;actor_ops=@(New-ActorOp $sid $spec.actor $phaseId $i);transition_ops=@();branches=$branches}
        $objectiveSteps += [ordered]@{id=$verbs[$i];label=($verbs[$i] -replace '_',' ');kind="command";command_id=$verbs[$i]}
    }
    $resolutionBranches=@(); for($i=0;$i -lt 3;$i++){ $resolutionBranches += [ordered]@{id="resolve_$($outcomes[$i])";condition=[ordered]@{type="command";command_id=$(if($i -eq 0){$verbs[-1]}elseif($i -eq 1){"refuse_sequence"}else{"fail_sequence"})};outcome=$outcomes[$i];objective_outcomes=[ordered]@{"${sid}_objective"=$(if($i -eq 0){"success"}elseif($i -eq 1){"ignore"}else{"failure"})}} }; $resolutionBranches += [ordered]@{id="resolve_interrupted";condition=[ordered]@{type="fact";fact_type="travel_departed"};outcome=$outcomes[3];objective_outcomes=[ordered]@{"${sid}_objective"="cancel"}}
    $phases += [ordered]@{id="resolution";label="Aftermath";arrival_feedback="The final arrangement settles around the chosen response.";exit_prompt="The marked exit remains clear in every aftermath.";terminal=$true;entry_conditions=@([ordered]@{type="always"});objective_ids=@();advance_after_actions=0;scene_ops=@();interaction_ops=@();actor_ops=@();transition_ops=@();branches=$resolutionBranches}
    $aftermath=[ordered]@{}; for($i=0;$i -lt $outcomes.Count;$i++){ $oid=$outcomes[$i]; $aftermath[$oid]=[ordered]@{label=($oid -replace '_',' ');revisit_feedback=("The " + ($oid -replace '_',' ') + " arrangement remains visible on revisit.");scene_ops=@(New-SceneOp $sid "aftermath_$oid" $oid $i);interaction_ops=@();actor_ops=$(if($i -eq 0){@(New-ActorOp $sid $spec.actor $oid ($i+1))}else{@()});service_ops=@();game_ops=@();route_ops=@()} }
    $cleanup=@(); foreach($o in $objects){$cleanup += [ordered]@{family="scene_ops";op="remove";receipt_id="${sid}_cleanup_$o";owner_namespace="scenario";stable_object_id=$o}}; $cleanup += [ordered]@{family="scene_ops";op="remove";receipt_id="${sid}_cleanup_safe_exit";owner_namespace="scenario";stable_object_id="safe_exit"}
    $captures=@("${sid}_arrival","${sid}_mid_sequence","${sid}_success","${sid}_failure","${sid}_refused","${sid}_interrupted","${sid}_partial_revisit","${sid}_terminal_revisit","${sid}_reduced_motion","${sid}_small_screen","${sid}_obstruction_overlay")
    return [ordered]@{scenario_id=$sid;sequence=[ordered]@{schema_version=2;local_state_schema=[ordered]@{pressure=[ordered]@{type="enum";default=$spec.pressure;values=@($spec.pressure,"resolved");visibility="public"}};phase_graph=[ordered]@{initial_phase="arrival";phases=$phases};objectives=@([ordered]@{id="${sid}_objective";label=$spec.title;progress_label="Sequence progress";steps=$objectiveSteps;outcomes=@("success","failure","ignore","cancel")});reentry_policy=[ordered]@{partial="resume";terminal="aftermath";expired="expired"};expiry=[ordered]@{boundary="night_end";after=1;policy="cleanup"};cleanup=[ordered]@{operations=$cleanup};aftermath=$aftermath;mechanic_tags=@($spec.pressure,"venue_$($spec.place)",$spec.connection);sequence_signature="UNREVIEWED";owner_exceptions=@();declared_targets=[ordered]@{scene_objects=@();interactions=@();actors=@();services=@();games=@();routes=@();anchors=@();zones=@()};fact_subscriptions=@([ordered]@{fact_type=$spec.connection;payload_equals=[ordered]@{};handler="set_local";inputs=[ordered]@{key="pressure";value="resolved"}},[ordered]@{fact_type="travel_departed";handler="publish_feedback";inputs=[ordered]@{message="Departure records the interrupted aftermath exactly once."}});completion_contract=[ordered]@{arrival_readable=$true;semantic_changes=$true;scenario_interaction=$true;action_boundaries=$true;choice_or_failure=$true;material_outcomes=$true;revisit_coverage=$true;world_connection=$true;primary_verb=$true;feedback_and_exit=$true}};authoring=[ordered]@{arrival_summary=$spec.arrival;player_verbs=$verbs;world_connections=@($spec.connection,"safe_exit");references=[ordered]@{events=@();games=@();services=@();items=@();actors=@($spec.actor);objects=@("scenario::safe_exit")};capture_ids=$captures;seed_evidence=[ordered]@{proof_seed="${sid}_seed";expected_outcomes=$outcomes;save_boundaries=@("arrival","mid_sequence","resolution");minimum_target_size=44;ordinary_seed_count=20;cleanup_idempotent=$true;reentry_idempotent=$true};masked_visual_explanations=[ordered]@{}}}
}

$package=[ordered]@{schema_version=1;package_id="env06_7_queen_public";handler_pack="queen_public";renderer_id="queen_public";scenarios=@()}
foreach($spec in $specs){$package.scenarios += New-Scenario $spec}
$json=$package | ConvertTo-Json -Depth 30
[IO.File]::WriteAllText((Join-Path (Get-Location) $OutPath), $json + [Environment]::NewLine, [Text.UTF8Encoding]::new($false))
Write-Host "Authored $($package.scenarios.Count) Package E scenarios at $OutPath"
